[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"
PLAYWRIGHT_BROWSERS_PATH = "0"

[[redirects]]
from = "/test-demo/*"
to = "/test-demo/index.html"
status = 200